blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = "blog"

urlpatterns =[
    path("",render_posts, name="posts"), 
    path("<int:post_id", post_detail, name="post_detail")
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from portfolio import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime 
class Post(models.Model):
  title = models.CharField(max_length=100)
  description = models.TextField()
  image = models.ImageField(upload_to='blog/images')
  date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

class Project(models.Model):
    title =CharField(max_length=100)
    descripcion =CharField(max_length=100)
    image = ImageField(upload_to='portfolio/images/')
    url = URLField(blank=True)

# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
def render_posts(resquest):
    posts = Post.objects.all()
    return render(resquest, 'posts.html',{'posts' : posts})

def post_detail(resquest, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(resquest, 'post_detail.html', {"post": post_id})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects =Project.objects.all()
    return render(request, 'home.html', {'projects': projects})

# Create your views here.

blog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}
<h1>Posts</h1>

<h2> {{post.title}}</h2>
<h3>{{post.date}}</h3>
<p>{{post.description|safe}}</p>
<img src="{{post.image.url}}" alt="{{post.title}}" width="300" height="500">
{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}
{% block content %}
<h1>Posts</h1>

{% for post in posts %}
<h2> {{post.title}}</h2>
<p>{{post.description|safe|truncatechars:100}}</p>
<p>{{post.date|date:'M d Y'|upper}}</p>
<img src="{{post.image.url}}" alt="{{post.title}}" width="300" height="500">
<br>
{% endfor %}
{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<header class="row bg-black">
  <div class="col-md-4">
    <img src="{% static 'portfolio/perfil.jpg' %}" />
  </div>

  <div class="col-md-8 my-auto p-4">
    <h1>I am <strong>Mera Laje</strong></h1>
    <h3>I'm a Python FullStack Developer</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis tempora perspiciatis molestias iusto ducimus
      soluta mollitia ratione, fuga praesentium, reiciendis minima! Facere, veniam! Omnis, quod molestias quo fugit enim
      vero vitae, cumque tenetur at, impedit provident dicta laudantium quia facilis consequuntur blanditiis iste
      laborum voluptatibus libero doloribus? Pariatur voluptatem obcaecati deserunt aperiam exercitationem nam voluptas
      rerum reprehenderit minima, earum impedit saepe eos ducimus fugit itaque a nulla omnis architecto laudantium
      blanditiis? Eius ipsum quidem enim architecto fugiat porro inventore libero praesentium aperiam nulla
      exercitationem nemo soluta, culpa impedit est et doloribus ut necessitatibus odit, dicta voluptate! Vero ab nulla
      placeat.</p>
    <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'portfolio/curriculum.pdf' %}" target="_blank">Download my CV</a>
  </div>
</header>

<div class="row my-4 text-center">

  <h3>My Projects</h3>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis, aperiam?</p>

  {% for project in projects %}
  <div class="col-md-4 p-4">
    <div class="card bg-black card-project">
      <img src="{{project.image.url }}" alt="{{project.title}}" class="card-img-top" />

      <div class="card-body">

        <h2>{{ project.title }}</h2>
        <p>{{ project.description }}</p>

        {% if project.url %}
        <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="__blank" rel="noreferrer">{{project.url}}</a>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>


{% endblock %}

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'portfolio/main.css' %}">
</head>
<body class="text-light">
    
    {% include 'partials/navbar.html' %}
    <div clas="container p-4">
    {% block content %}

    {% endblock %}
</div>
    <footer>footer</footer>
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">Mera laje</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
          </li>
          <li class="nav-item d-flex aling-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/curriculum.pdf' %}" target="_blank">Download CV</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>